### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by bmulholland** [aspose-words-cloud/aspose-words-cloud-ruby#4]
I see mixed signals about whether this gem is being maintained. On the one hand, there's active CI updates getting pushed and [even some new examples added recently](https://github.com/aspose-words-cloud/aspose-words-cloud-ruby/commit/e43bb187983e63b453acac5ecc5855d167b6f3e8).

And yet, all the dependencies are years out of date.

What's the status here?

**Comment by YaroslawEkimov** [comment]
Yes, this gem is maintained, but we usually  don't update dependencies every release because there are a lot of clients who for some reasons use old version of ruby. Common approach for updating dependencies is when there is some vulnerabilities are found at dependecy gem or package.
But as there are some abandoned gems and out of date which we used before, we are going to update them with minimal version of ruby that we support, based on other ticket you created.
Thanks for pointing out for issues we can solve to make developers life easier.

**Comment by bmulholland** [comment]
@YaroslawEkimov That all makes sense, but if so, perhaps it would be a good idea not to set maximum versions of things?

As it stands, the gemfile _requires_ ruby 2.3 (`~>`), which, [despite what the README claims](https://github.com/aspose-words-cloud/aspose-words-cloud-ruby#dependencies), means more recent ruby versions _cannot_ be used. Similarly, faraday and mimemagic are fixed to very old versions, again meaning that new versions cannot be used in the same project as this gem.

**Comment by YaroslawEkimov** [comment]
The new release of ruby sdk will be published very soon, where I fixed things you mentioned in your issues.

**Comment by bmulholland** [comment]
Hey - thanks for the update. We've confirmed if works and deployed the updates to production. Appreciate it!
